---
- name: Sync Minecraft server data to S3
  hosts: servers
  gather_facts: false
  become: true

  tasks:
    - name: Sync Minecraft server files to S3 before destroy
      ansible.builtin.command: >
        aws s3 sync /home/ec2-user/minecraft-data s3://chris-terraform-minecraft-bucket/server_files