name: Test and Push Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # # Test & deploy dockerimage to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Minecraft Docker image
      #   run: docker build -t minecraft-server ./docker

      # - name: Run Minecraft server container
      #   run: |
      #     docker run -d --name mc-server-test -p 25565:25565 minecraft-server
      #     sleep 10  # wait for server to fully start

      # - name: Install nmap
      #   run: sudo apt-get update && sudo apt-get install -y nmap

      # - name: Test port 25565 with nmap
      #   run: |
      #     nmap -p 25565 localhost | grep "25565/tcp open" || (echo "Port 25565 not open!" && exit 1)

      # - name: Push to Docker Hub (if test passed)
      #   run: |
      #     docker tag minecraft-server ${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/minecraft-server:latest

      # Terraform test and deploy EC2 instance
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
      
      - name: Get EC2 Public IP from Terraform
        id: get_ip
        run: |
          cd terraform
          IP=$(terraform-bin output -raw instance_public_ip)
          echo "$IP"
          echo "ip=$IP" >> "$GITHUB_OUTPUT"

      - name: Use the IP
        run: echo "The EC2 public IP is ${{ steps.get_ip.outputs.ip }}"   

      - name: Write SSH key
        run: |
          cd ansible
          echo "${{ secrets.SSH_MINECRAFT_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Create Ansible inventory file
        run: |
          cd ansible
          echo "[servers]" > ./inventory/hosts.ini
          echo "${{ steps.get_ip.outputs.ip }} ansible_user=ec2-user ansible_ssh_private_key_file=key.pem" >> ./inventory/hosts.ini

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      
      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i ./inventory/hosts.ini ./playbooks/minecraft.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Wait and test Minecraft port (25565) on EC2
        run: |
          echo "Waiting 20 seconds for Minecraft server to start..."
          sleep 20
          echo "Testing EC2 at ${{ steps.get_ip.outputs.ip }}"
          nmap -Pn -p 25565 ${{ steps.get_ip.outputs.ip }} | grep "25565/tcp open" || (echo "Port 25565 not open!" && exit 1)
        
      # Destroy Runner when done
      - name: Cleanup container
        if: always()
        run: |
          # docker stop mc-server-test || true
          # docker rm mc-server-test || true
          cd terraform
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
